### ISSUE TITLE
Azure SD with Public IP Address: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dgiagio** [prometheus/prometheus#10271]
## Version
Docker image `prom/prometheus`, tags `latest` and `main`, both have the same problem.

## Problem
We're receiving a panic from Azure SD plugin whenever it tries to enumerate our VMs. The problem is caused by an incorrect nil check as seen below:

https://github.com/prometheus/prometheus/blob/579331446a04503b2b1515767e7ceaceab2c6342/discovery/azure/azure.go#L374-L376

## Fix
The current code is checking `ip.PublicIPAddress.PublicIPAddressPropertiesFormat` but is dereferencing `ip.PublicIPAddress.IPAddress`. We should nil check `ip.PublicIPAddress.IPAddress` instead.

## Stacktrace
```
Feb 08 17:14:17 prometheus docker[8302]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 08 17:14:17 prometheus docker[8302]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xeb0ac1]
Feb 08 17:14:17 prometheus docker[8302]: goroutine 776 [running]:
Feb 08 17:14:17 prometheus docker[8302]: github.com/prometheus/prometheus/discovery/azure.(*Discovery).refresh.func1(0xd9bebd0f7c815613, {{0xc00194db80, 0x92}, {0xc001950228, 0x11}, {0xc001950240, 0x11}, {0xc0019726f0, 0x21}, {0xc001a62590, ...}, ...})
Feb 08 17:14:17 prometheus docker[8302]:         /app/discovery/azure/azure.go:375 +0x7a1
Feb 08 17:14:17 prometheus docker[8302]: created by github.com/prometheus/prometheus/discovery/azure.(*Discovery).refresh
Feb 08 17:14:17 prometheus docker[8302]:         /app/discovery/azure/azure.go:321 +0xd52
```

**Comment by LeviHarrison** [comment]
Thanks for your report. This was theoretically fixed in https://github.com/prometheus/prometheus/pull/5587, and https://github.com/prometheus/prometheus/pull/5587#discussion_r286171167 explains why `ip.PublicIPAddress.PublicIPAddressPropertiesFormat` is used instead. I don't think that check works though, as can be seen in this example (and the bug you found): https://go.dev/play/p/qDzVx0mnoXL.

**Comment by c054864** [comment]
We've started receiving the same panic with our prometheus implementation today, out the blue with no changes. 

````
Feb 10 14:40:34 xxxxx prometheus: panic: runtime error: invalid memory address or nil pointer dereference
Feb 10 14:40:34 xxxxx prometheus: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xb419b8]
Feb 10 14:40:34 xxxx prometheus: goroutine 9930314 [running]:
Feb 10 14:40:34 xxxx  prometheus: github.com/prometheus/prometheus/discovery/azure.(*Discovery).refresh.func1(0xc0cf006aa0, 0xc0e7a0b050, 0xc15b820840, 0xc0d7ff5400, 0x2a1a460, 0xc13b79a300, 0x7, 0xc112e50e60, 0x94, 0xc14b363f80, ...)
Feb 10 14:40:34 xxxx prometheus: /app/discovery/azure/azure.go:339 +0xb38````

prometheus, version 2.13.0 (branch: HEAD, revision: 6ea4252299f542669aca11860abc2192bdc7bede)
  build user:       root@f30bdad2c3fd
  build date:       20191004-11:25:34
  go version:       go1.13.1

**Comment by LeviHarrison** [comment]
That's interesting because this bug has been present since v2.9, but only now it's showing up. Maybe something changed on Azure's side?

**Comment by LeviHarrison** [comment]
I've opened #10280 to fix this.

**Comment by LeviHarrison** [comment]
This will be fixed in 2.33.2.

**Comment by jaydrue** [comment]
We also discovered this today out of the blue. We were running on an older version. Upgrading to the latest version 2.33.1 did not help to solve the issue.

Here are the logs
```
ts=2022-02-11T12:18:17.324Z caller=main.go:896 level=info msg="Server is ready to receive web requests."
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xef9b81]

goroutine 580 [running]:
github.com/prometheus/prometheus/discovery/azure.(*Discovery).refresh.func1(0x0, {{0xc001eae790, 0xa2}, {0xc000036340, 0x19}, {0xc000036420, 0x19}, {0xc001dbdd10, 0x21}, {0xc001b46d80, ...}, ...})
        /app/discovery/azure/azure.go:365 +0x7a1
created by github.com/prometheus/prometheus/discovery/azure.(*Discovery).refresh
        /app/discovery/azure/azure.go:311 +0xd52
```

**Comment by roidelapluie** [comment]
I guess azure changed something in their API's.

**Comment by LeviHarrison** [comment]
Yeah, unfortunately upgrading won't help as the fix hasn't made a release yet. We're hoping to get 2.33.2, which has the fix, out as soon as possible. In the meantime, you can build the patched version yourself if you wish from the `release-2.33` branch.

**Comment by roidelapluie** [comment]
A new release is out.

**Comment by LeviHarrison** [comment]
Thanks for your work getting the release out so quickly!

**Comment by jaydrue** [comment]
Maybe some interesting context:

We are running with multiple subscriptions and have all VMs that we monitor in 1 subscription, and only scalesets in the other, plus one additional VM in both subscriptions where prometheus is hosted on a single VM.
Prometheus is working perfectly in the subscription where we don't have any VMs deployed. Just for the fun of it, I deployed a VM there to see if I can provoke the same error in that subscription. And as soon as the deployment was finished, that one went down as well.

**Comment by roidelapluie** [comment]
Mmmh the last panic you have sent is about line 364.

**Comment by dgiagio** [comment]
Pulled the fix, and still having the error. The line with the error is now `364`. Seems like `ip` itself is `nil`.

https://github.com/prometheus/prometheus/blob/b4714db0a6108aa7ef9c13daa12ac8eb6b5504a1/discovery/azure/azure.go#L363-L366

**Comment by LeviHarrison** [comment]
Interesting. So I guess we need to `nil`-check the `ip` now?

**Comment by roidelapluie** [comment]
Can you please try #10289?

Pre-built binaries from our CI: https://app.circleci.com/pipelines/github/prometheus/prometheus/15928/workflows/bb6f9612-032a-407e-a204-66282a431552/jobs/75697/artifacts

**Comment by jaydrue** [comment]
> Can you please try #10289?
> 
> Pre-built binaries from our CI: https://app.circleci.com/pipelines/github/prometheus/prometheus/15928/workflows/bb6f9612-032a-407e-a204-66282a431552/jobs/75697/artifacts

Yes! You guys are amazing! That one works!

**Comment by roidelapluie** [comment]
2.33.3 has been released.
