### ISSUE TITLE
Cannot create Kubernetes discovery

### ISSUE THREAD

**Issue by coocla** [prometheus/prometheus#1288]
My k8s apiserver without any verification，so my prometheus.yaml is:
```
- job_name: 'kubernetes'
  kubernetes_sd_configs:
  - masters:
    - 'http://172.16.1.12:8080'
    in_cluster: false
```

When I start, I get 
```
prometheus, version 0.16.1 (branch: release-0.16.1, revision: 968ee35)
  build user:       fabianreinartz@macpro
  build date:       20151016-13:19:57
  go version:       1.5
INFO[0000] Loading configuration file prometheus.yml     source=main.go:196
ERRO[0000] Cannot create Kubernetes discovery: open : no such file or directory  source=targetmanager.go:424
INFO[0000] Loading series map and head chunks...         source=storage.go:262
INFO[0000] 309 series loaded.                            source=storage.go:267
INFO[0000] Listening on :9090                            source=web.go:223
```

Can you help me，Which file I lack?

**Comment by beorn7** [comment]
Looks like a problem reading the CA certificate. You might want to try setting a `tls_config` with `insecure_skip_verify: true`.

**Comment by jimmidyson** [comment]
That's a terrible error message - hope to get some time to clean it up soon.

**Comment by jimmidyson** [comment]
Ah looks like I've already done that in HEAD so should be in next release.

**Comment by jimmidyson** [comment]
Fixed in 7ff5cc6

**Comment by jimmidyson** [comment]
This was actually a bug reading the service account token file IIRC.

**Comment by beorn7** [comment]
OK, closing this then. Please re-open if it turns out to be a different issue.

**Comment by coocla** [comment]
@beorn7   setting a `is_config` with `insecure_skip_verify: true` not effective， So I may have to wait for the next release or setting cadvisor address replace `kubernetes_sd_configs` ?

I try setting `is_config` with `ca_file`、`cert_file`、`key_file`  error still exists.

**Comment by jimmidyson** [comment]
As I said above this is due to bearer token file handling when running in a pod, fixed in master. If you're running a Docker container then you can use `prom/prometheus:master` image that contains the fix, although be aware there are some changes to Prometheus config that you would need to do.
