### ISSUE TITLE
Cannot scrape targets specified by mDNS name

### ISSUE THREAD

**Issue by moio** [prometheus/prometheus#2537]
**What did you do?**

I am trying to scrape a target that runs `node_exporter` by its mDNS name (published through Avahi) in my local network (see configuration below).

**What did you expect to see?**

The same behavior as specifying the IP address in `targets` (which works as expected).

**What did you see instead? Under which circumstances?**

State of the endpoint is `DOWN` in http://ptometheus.local:9090/targets, while `ping` works as expected.

**Environment**

* System information:

```
# uname -srm
Linux 4.4.21-69-default x86_64
```

* Prometheus version: 

Latest released:
```
# /opt/prometheus/prometheus -version
prometheus, version 1.5.2 (branch: master, revision: bd1182d29f462c39544f94cc822830e1c64cf55b)
  build user:       root@a8af9200f95d
  build date:       20170210-14:41:22
  go version:       go1.7.5
```

Also reproduced on self-built `master`:
```
# /opt/prometheus/prometheus -version
prometheus, version 1.5.2 (branch: master, revision: 29f05680a29afe9aa6cf119563e99723a41765bd)
  build user:       silvio@lenovo
  build date:       20170328-11:31:33
  go version:       go1.7.3
```

* Prometheus configuration file:
```
global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'avahi'
    static_configs:
      - targets: ['avahi.local:9100']
```

**Comment by msiebuhr** [comment]
Slightly related, I recently implemented [mDNS service discovery](https://github.com/msiebuhr/prometheus-mdns-sd).

It looks for things advertising `_prometheus-http._tcp` (and ditto HTTPS) over zeroconf/mDNS and regularly dumps what it found. You won't need the zeroconf hostnames, but you will need to publish your service for consumption by prometheus.

**Comment by brian-brazil** [comment]
We support DNS, with would require specific mDNS support to be added.

**Comment by discordianfish** [comment]
Do we want to support that? I just realize my new home router isn't adding dhcp clients with their hostname to DNS, so would like to use mdns for my setup at home to discover exporters.

**Comment by brian-brazil** [comment]
We've a moratorium on new SDs, and mDNS isn't exactly something I'd expect to see in a production setup.

**Comment by discordianfish** [comment]
Arguably it's by far the most common SD mechanism. Not in your typical server infrastructure but using Prometheus in a home network/IoT is IMO a reasonable use case.

**Comment by brian-brazil** [comment]
There's always file_sd.

**Comment by msiebuhr** [comment]
I think you're confusing two faces of mDNS:

 1. RFC6762 - `.local` hostnames and resolving them on a local network.
 2. RFC6763 - mDNS service discovery (eg. `_http._tcp.local` for discovering all local web servers)

They happen to share the same means (and name), but to achieve two quite different goals.

As to the first, it is worth noting that Go hasn't always been nice to resolve `.local` names, ex: https://github.com/golang/go/issues/16739. I haven't played with it on any recent Go-versions, so I can't attest to the current state of things. Wrapping things in `file_sd` won't make much difference in this case.

I sort-of-skirted the issue by using the service-discovery part (see https://github.com/msiebuhr/prometheus-mdns-sd) where I return the resolved addresses to Prometheus. (Look at https://github.com/prometheus/prometheus/pull/1903 for some history and further discussion).

**Comment by discordianfish** [comment]
@msiebuhr What were the main reasons to close the PR? I'd actually love to see this in Prometheus, with the influx of people using Prometheus for IoT use cases etc.

**Comment by msiebuhr** [comment]
It drags in quite a few large dependencies (low-level networking to get mDNS working), and I was told in private conversation (perhaps @brian-brazil ; cannot remember) that new service discovery mechanism preferably should be built outside core prometheus.

But yes, I generally find it weird (from a hobbyist/IoT point-of-view) that Prometheus comes with complex discovery mechanisms for some really big systems and everyone else must implement some custom cron/daemon thing poking at `file_sd`.

**Comment by discordianfish** [comment]
@msiebuhr I fully agree with this. I don't know why proprietary, vendor specific SD mechanisms for things like triton or azure are in scope while the most widely deployed open mechanism isn't.

I know that @SuperQ would also like to see mDNS support. So if we can find lazy consensus here, I'd probably call in a official vote on this.

**Comment by brian-brazil** [comment]
We continue to have a moratorium on new SD mechanisms, and once the example file_sd code is in the plan is to close all existing feature requests and point to that instead.

SDs take a lot of work to maintain, and history shows that there's little interest in doing so.

**Comment by SuperQ** [comment]
I don't agree with this plan.

**Comment by brian-brazil** [comment]
There's no sign of an end to the conditions that gave us the moratorium, and I'd rather clearly set expectations with the various requestors of SDs - some of whom have been waiting for 2+ years - than continue to give them false hope. Between the file_sd example and setting expectations I'm hoping that there'll be a surge in the development&maintenance of these by 3rd parties, rather than the current stream of +1s on issues which are ignored.

This structure gives us the option of pulling in some of the SDs into Prometheus in the future when things are healthier, but we continue to be unable to accept new SDs or even maintain what we already have.

**Comment by Gaelan** [comment]
This bug—which is specifically about resolving `.local` domain names (that come from somewhere else, such as `static_configs`), not using mDNS for service discovery—seems to have been fixed by https://github.com/golang/go/issues/16739. It should probably be closed, and a separate issue opened for a possible future SD mechanism.

**Comment by SuperQ** [comment]
Yes, we also ended the moratorium on new service discovery, so a feature design issue would be appropraite.

**Comment by moio** [comment]
> This bug—which is specifically about resolving `.local` domain names (that come from somewhere else, such as `static_configs`), not using mDNS for service discovery—seems to have been fixed by [golang/go#16739](https://github.com/golang/go/issues/16739). It should probably be closed

According to my understanding this is not the case - the Go issue above is not really about implementing mDNS resolution in the pure Go resolver.

Reproducer (`main.go`):

```go
package main

import "fmt"
import "net"

func main() {
	name, err := net.LookupHost("prometheus.local")
	if err == nil {
		fmt.Println(name[0])
	} else {
		fmt.Println(err.Error())
	}
}
```

On the commandline:
```
> go version
go version go1.12.17 linux/amd64

> GODEBUG=netdns=cgo go run ./resolve.go
192.168.187.15

> GODEBUG=netdns=go go run ./resolve.go
lookup diskstation.local on 192.168.187.1:53: no such host
```

So to me the original description of this issue is still valid.

**Comment by fornellas** [comment]
There's something odd with Prometheus... pure Go as per above comment seems to work fine. From [go documentation](https://pkg.go.dev/net), it should be using `cgo` resolver:

> ...and when the name being looked up ends in .local or is an mDNS name.

So, it should be working for `.local` targets.

I even tried running my Prometehus with `GODEBUG=netdns=cgo`, but scraping still fails:

```
Get "http://brown.local:9100/metrics": dial tcp: lookup brown.local on 127.0.0.53:53: no such host
```

The error tells me Prometheus is talking to the DNS server from my `resolv.conf`, and NOT using what's at `nsswitch.conf`, as it'd be expected if it was using `cgo` resolver. `getent hosts brown.local` works just fine though.

My guess is that Prometheus is using some custom code for name resolution, that does not leverage Go's "just work" approach for mDNS for `.local` domains.

**Comment by moio** [comment]
@fornellas see https://github.com/prometheus/prometheus/pull/2538. The pure Go resolver is forced at build time, so `GODEBUG=netdns=cgo` does not have effect.

**Comment by mahtin** [comment]
Can I poke on this issue? It was opened on March/2017 and the last comment was December/2021 and while there's been some interesting discussion, it has not led to any resolving of the situation-at-hand.

I would like to point out that in this day-n-age, one would expect an MDNS based hostname (RFC6763  etc) to be accepted by ALL software running on a modern-day operating system. If the `host(1)` command shows resolution of a hostname, then similar resolution should be provided. Sadly, most of the discussion here is all about GoLang's purity vs actually solving @moio's initial (five and half year old) issue.

While I know the right thing for me to do it to buck up and send in a PR; sadly, I'm a C & Python kinda person and GoLang isn't my forte. But I am someone that's used Prometheus for a long time and was shocked when I spun Prometheus up at home to do some testing and found it would not cooperate across my two simply configured hosts within my `.local` DNS range. I was basically shocked (until I read this, then I was further shocked). 

Summary: If all other system s/w can resolve a host in the `.local` domain, so should Prometheus.

**Comment by roidelapluie** [comment]
I welcome contributions regarding this , maybe with a new service discovery provider, mdns, based on https://github.com/hashicorp/mdns

**Comment by SuperQ** [comment]
There's also an mDNS plugin for CoreDNS. https://coredns.io/explugins/mdns/

**Comment by cjjeakle** [comment]
Hi All, I ran into this and wanted to follow-up to help any others who stumble across this issue.

There's great discussion here, in PRs, and in the official docs. The solution @msiebuhr came up with is super cool. Alas, none of my hosts announce their services available and I'm hoping to just centrally configure everything. Their approach of using another service to handle MDNS resolution and to write the result to a file is really neat and easy to reason about, which is appealing.

That got me pondering their approach and reading the docs. It turns out file-based service discovery is super flexible and shockingly easy to use. I ended up hacking together a quick solution to get support for MDNS `*.local` hostnames and I figured I should share to help any others who want it:

# How the solution works:
1. List the hosts and tags you want to scrape in a json file. I went with files named `/etc/prometheus/lan-blackbox-hosts.json` and `/etc/prometheus/lan-node-hosts.json`.
1. Configure a systemd timer service that runs a python script. It reads in those files and writes out the resolved ip (or ip:port) in place of the hostnames (or hostname:port), and preserves the tags you provide with the input.
1. Configure prometheus to scrape the targets in those output json files, rather than manually enumerating the scrape targets inline in `prometheus.yml`.
1. Sit back and relax, it's all on autopilot now!

# Operating assumptions
(feel free to regex replace these to your preference)
* Prometheus configs live in `/etc/prometheus/`
* Prometheus is storing it's runtime-mutable data in `/var/lib/prometheus/`
* You'd like to run prometheus-related services under a service user named `prometheus`
    * Add one via `sudo useradd --system prometheus`
    * You'll want to chown any folders that user will write to (i.e., `sudo chown -R prometheus /var/lib/prometheus/`)

# Hack together support for MDNS using Custom Service Discovery
Sources and inspiration:
https://prometheus.io/docs/guides/file-sd/
https://github.com/prometheus/prometheus/pull/1903
https://github.com/msiebuhr/prometheus-mdns-sd
https://prometheus.io/blog/2015/06/01/advanced-service-discovery/#custom-service-discovery
https://prometheus.io/blog/2015/08/17/service-discovery-with-etcd/

`sudo mkdir /opt/mdns-resolve/`
`sudo vim /opt/mdns-resolve/mdns-resolve.py`
```
import argparse
import json
import socket
import sys
import urllib.parse

# Get the input and output files as command line arguments
parser = argparse.ArgumentParser()
parser.add_argument('in_file', help='The input JSON file')
parser.add_argument('out_file', help='The output JSON file')
args = parser.parse_args()

# Load the input data into a holder object
with open(args.in_file, 'r') as input_data:
    lan_description = json.load(input_data)

# Resolve the host names to IP addresses
for lan_hosts in lan_description:
    resolved_ips = [];
    for host_port in lan_hosts['hosts']:
        parsed_url = urllib.parse.urlsplit('//' + host_port);
        try:
            ip = socket.gethostbyname(parsed_url.hostname);
            if parsed_url.port:
                ip = ip + ":" + str(parsed_url.port);
            resolved_ips.append(ip);
        except socket.gaierror:
            sys.stderr.write("Failed to resolve hostname: {host}");
    del lan_hosts['hosts']
    lan_hosts['targets'] = resolved_ips;

# Write the updated list to the output JSON file
with open(args.out_file, 'w') as f:
    json.dump(lan_description, f, indent=4)
```

`sudo vim /etc/prometheus/lan-blackbox-hosts.json`
```
[
    {
        "hosts": ["some_lan_host1.local"],
        "labels": {
            "label1": "label_value1",
            "label2": "label_value2"
        }
    },
    {
        "hosts": ["some_lan_host2.local"],
        "labels": {
            "label1": "label_value1",
            "label2": "label_value2"
        }
    }
]
```

`sudo vim /etc/prometheus/lan-node-hosts.json`
```
[
    {
        "hosts": ["some_lan_host.local:9100"],
        "labels": {
            "label1": "label_value1",
            "label2": "label_value2"
        }
    }
]
```

`sudo vim /etc/systemd/system/prometheus-mdns-resolve.service`
```
[Unit]
Description=Resolves MDNS Hosts for Prometheus
After=network-online.target

[Service]
User=prometheus
Type=oneshot
ExecStart=\
python3 /opt/mdns-resolve/mdns-resolve.py \
/etc/prometheus/lan-blackbox-hosts.json /var/lib/prometheus/lan-blackbox-targets.json && \
python3 /opt/mdns-resolve/mdns-resolve.py \
/etc/prometheus/lan-node-hosts.json /var/lib/prometheus/lan-node-targets.json
```

`sudo vim /etc/systemd/system/prometheus-mdns-resolve.timer`
```
[Unit]
Description=Refreshes resolved MDNS hostnames for Prometheus every 5m
After=network-online.target

[Timer]
OnBootSec=0min
OnCalendar=*:0/5

[Install]
WantedBy=timers.target
```

```
sudo systemctl daemon-reload && \
sudo systemctl enable prometheus-mdns-resolve.timer && \
sudo systemctl start prometheus-mdns-resolve.timer && \
sudo systemctl status prometheus-mdns-resolve.timer
```

Seeing what's up:
* `sudo systemctl status prometheus-mdns-resolve.timer`
* `sudo systemctl status prometheus-mdns-resolve.service`
* `sudo journalctl -u prometheus-mdns-resolve.service`

Consume in prometheus by replacing relevant `static_configs:` entries with something like:
```
    file_sd_configs:
      - files:
        - /var/lib/prometheus/lan-node-targets.json
        refresh_interval: 5m
```
or
```
    file_sd_configs:
      - files:
        - /var/lib/prometheus/lan-blackbox-targets.json
        refresh_interval: 5m
```
etc

---

Hope this helps any folks who stumble across this issue! Happy holidays!

**Comment by yangm97** [comment]
https://github.com/brutella/dnssd seems to be a lightweight, well tested library for mDNS service handling. 

Also +1 on the IoT usecase.

**Comment by krajorama** [comment]
Hello from the bug scrub: this seems like a legit use case perhaps better suited for working through https://prometheus.io/docs/prometheus/latest/configuration/configuration/#http_sd_config or https://prometheus.io/docs/guides/file-sd/. Contributions welcome.

**Comment by fornellas** [comment]
If anyone interested, I've implemented HTTP SD:
https://github.com/fornellas/prometheus-mdns-http-sd
"works for me", hopefully for others as well :-D

**Comment by benkeil** [comment]
7 years and no solution?

**Comment by astrostl** [comment]
Created discussion #18991 to gauge interest on AI-driven resolution

**Comment by machine424** [comment]
Hello from Bug Scrub.

We'd like to highlight the limitations of `dns_sd_config` in https://prometheus.io/docs/prometheus/latest/configuration/configuration/#dns_sd_config for better visibility.

I'd be even better if we have new tests/cases added in https://github.com/prometheus/prometheus/blob/main/discovery/dns/dns_test.go to confirm/validate that.
