### ISSUE TITLE
Frequent config reloading cause multi connection of same target 

### ISSUE THREAD

**Issue by ZeeShen** [prometheus/prometheus#3577]
I set a cron job that check prometheus config repo and SIGHUP prometheus when config changes. 

A bug in the job cause prometheus reloading config every minute. Then prometheus kept logging
error like `too many open files`.

![image](https://user-images.githubusercontent.com/3369662/33875666-e5599be0-df5d-11e7-995a-2a8eb191c05c.png)
↑ Open fd and goroutine count increasing after setting ulimit to 4096, target count 700+, avg scrape duration 60ms.

Then I found most of these opening fds were socket files. And with `netstat`, I found prometheus kept several(like 5 or 6) `ESTABLISHED` connections with same targets. 

Not familiar with the code base but it might be helpful to check [here](https://github.com/prometheus/prometheus/blob/v2.0.0/retrieval/scrape.go#L230) that scrape pool will start new scrape loops when config changes. Maybe something wrong with scrape loop's run or stop?

I fixed the cron job and prometheus is running correctly now(open fd 600+, socket 500+). But I think maybe the prometheus server should deal with this frequent reloading situation. Or maybe something wrong with my configuration?

**Environment**

* System information:

Linux 4.4.0-62-generic x86_64

* Prometheus version:

```prometheus, version 2.0.0 (branch: HEAD, revision: 0a74f98628a0463dddc90528220c94de5032d1a0)
  build user:       root@615b82cb36b6
  build date:       20171108-07:11:59
  go version:       go1.9.2
```
running with 
```--storage.tsdb.path=/mnt/prometheus --config.file=/xxx/prometheus.yml --storage.tsdb.retention=360h```

and the prometheus.yaml is kinda big, main part is an ec2-sd and a file-sd of static targets.

**Comment by Gouthamve** [comment]
https://github.com/prometheus/prometheus/pull/2830 Should fix this. Will get around to it soon.

**Comment by ZeeShen** [comment]
Reloading only when config changes is a good solution for my case. 

But what if the config is actually changes and should be reloaded frequently? Like add or remove some targets every minute, most targets remains unchanged and this multi-connection may still happen?

**Comment by Gouthamve** [comment]
Hi, you should use file SD for that.

**Comment by brian-brazil** [comment]
Is this still happening?

**Comment by ZeeShen** [comment]
We gave prometheus a BIG fd limit to avoid such `too many open files` error. Will open new issue if we found this happen again.
