### ISSUE TITLE
Add an info level annotation if an API request contains future timestamps

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#4966]
So far, the query model is very clear:

For any point in time _t<sub>n</sub>_, we process…
- … for instant vectors the most recent data point with _t_ ≤ _t<sub>n</sub>_, as long as the series is not stale and _t<sub>n</sub>_ – _t_ is smaller than the `--query.lookback-delta`.
- … for range vectors the data points within the specified range, where the range ends at _t<sub>n</sub>_.

The returned results are time-stamped at _t<sub>n</sub>_.

If _t<sub>n</sub>_ is in the future, weird things happen, however:
- Obviously, the query will yield dramatically different results if executed again when _t<sub>n</sub>_ is not in the future anymore.
- If _t<sub>n</sub>_ is in the future by an amount close to `--query.lookback-delta`, results will start to disappear, which is especially problematic if the query is an aggregation, so that only _some_ of the expected series are included.
- For range vectors, the number of samples within the range will decrease the farther _t<sub>n</sub>_ is in the future. Results will become gradually more noise, until `rate` and friends will stop yielding results  at all once there is only one data point in the range. In other cases, there will be no result anymore if no data point is in the range. This again is especially problematic with aggregations.

State of the art is, IMHO, that we consider queries from the future an accident, resulting from time skew (we even warn in the web UI about time), and we return results as described above.

As you might have noticed, [Grafana is now using future query times deliberately](https://github.com/grafana/grafana/pull/10434). It is doing so for consistently aligned query times in range queries, e.g. a range query with a step length of 30s will query for data points at the full and half minute always. To not miss the most recent data, Grafana will, in this case, query for up to 30s into the future and then (presumably) still cut the displayed graph to the present. This strategy collides with the implications I have listed above, creating [issues](https://github.com/grafana/grafana/issues/13419).

One might argue that Grafana's approach here is simply wrong, and indeed, the feature is somewhat controversial, see the [discussion in the relevant PR](https://github.com/grafana/grafana/pull/10434).
However, it triggered some thinking on my side if we should handle queries from the future in a different way. Even if we disregard Grafana's current use case, there will be more that will ask Prometheus to predict the future, accidentally or deliberately.

Mutually exclusive options that come to mind:
1. Refuse queries from the future (with a certain grace period in the order of seconds at most).
2. Don't return results for the future, i.e. no results at all for an instant query (with the same grace period again) and only return results for timestamps in the past for range queries, e.g. if a range query requests timestamps _t<sub>–40s</sub>_, _t<sub>–10s</sub>_, _t<sub>+20s</sub>_, and _t<sub>+50s</sub>_, only return results for _t<sub>–40s</sub>_ and _t<sub>–10s</sub>_
3. Adjust future timestamps to the present, i.e. an instant query for _t<sub>+20s</sub>_ will return the result for _t<sub>0s</sub>_, __timestamped as such__, while a range query will coalesce all timestamps in the future into one at _t<sub>0s</sub>_, for which it will return a result, __timestamped as such__, e.g. if a range query requests timestamps _t<sub>–40s</sub>_, _t<sub>–10s</sub>_, _t<sub>+20s</sub>_, and _t<sub>+50s</sub>_, return results for _t<sub>–40s</sub>_, _t<sub>–10s</sub>_, and _t<sub>0s</sub>_.

There are certainly many pros and cons. 1. would break current Grafana hard. 2. would directly counteract Grafana's strategy to also get the freshest result. 3. has the advantage that it does what probably most deliberate users of future timestamps want.

Of course, there is the overarching question if this is a breaking change only possible in Prometheus 3, even if we believe it is a change we want.

**Comment by brian-brazil** [comment]
> Even if we disregard Grafana's current use case, there will be more that will ask Prometheus to predict the future, accidentally or deliberately.

It used to do that via interpolation, and that behaviour was removed. Predictions are a different matter, we have predict_linear for that.

I don't think there's anything we can sanely/safely do here, I'd suggest that Grafana not request data from the future.

> Of course, there is the overarching question if this is a breaking change only possible in Prometheus 3, 

We do accept scrapes containing metrics up to 10 minutes into to the future as a safety measure, while allowing for time skew. Any of the proposed changes could break such users, and 3 violates timestamp and step semantics.

**Comment by beorn7** [comment]
To be clear: This is not about actual prediction. The title refers to the fact that Prometheus returns a potentially very problematic result when asked for a sample from the future, without any flagging.

**Comment by brian-brazil** [comment]
One thing we could maybe do is return back the maximum timestamp currently in the tsdb as an additional piece of information in queries.

**Comment by beorn7** [comment]
The Grafana problem has been solved by https://github.com/grafana/grafana/pull/16110 .

I'll leave this issue open nevertheless. I think adding the maximum timestamp currently in the tsdb as suggested above is a good first step to at least make the problem of “querying the future” discoverable. I also think we should document the stability of query results over time explicitly (grace period for samples added with timestamps in the past and the future, ingestion delay (how large can it become in practice, actually? Prom1 had a problem with indexing delay, which shouldn't exist anymore, but I guess there will still be some finite ingestion delay), rule evaluation delay, mutation of the database by the new vertical black merges, …).

**Comment by brian-brazil** [comment]
> mutation of the database by the new vertical black merges

Those shouldn't be an issue, as it's either a compaction or a reload.

**Comment by beorn7** [comment]
> Those shouldn't be an issue, as it's either a compaction or a reload.

I don't understand the relevance.

If I add an overlapping block, I'll “change the past” and thus it is important to keep in mind if a user of the query API wants to do caching. No?

**Comment by brian-brazil** [comment]
Ah right. Deletion and retention also will have that effect.

**Comment by husoule** [comment]
I have set the query.lookbackDelta=5s。 why I still get the data of future 5m.
![image](https://user-images.githubusercontent.com/5336915/89610321-c50a9100-d8ac-11ea-8b7f-339a091eda12.png)
current time is:
![image](https://user-images.githubusercontent.com/5336915/89610335-cb990880-d8ac-11ea-91a9-aca78137e774.png)

**Comment by husoule** [comment]
> So far, the query model is very clear:
> 
> For any point in time _tn_, we process…
> 
> * … for instant vectors the most recent data point with _t_ ≤ _tn_, as long as the series is not stale and _tn_ – _t_ is smaller than the `--query.lookback-delta`.
> * … for range vectors the data points within the specified range, where the range ends at _tn_.
> 
> The returned results are time-stamped at _tn_.
> 
> If _tn_ is in the future, weird things happen, however:
> 
> * Obviously, the query will yield dramatically different results if executed again when _tn_ is not in the future anymore.
> * If _tn_ is in the future by an amount close to `--query.lookback-delta`, results will start to disappear, which is especially problematic if the query is an aggregation, so that only _some_ of the expected series are included.
> * For range vectors, the number of samples within the range will decrease the farther _tn_ is in the future. Results will become gradually more noise, until `rate` and friends will stop yielding results  at all once there is only one data point in the range. In other cases, there will be no result anymore if no data point is in the range. This again is especially problematic with aggregations.
> 
> State of the art is, IMHO, that we consider queries from the future an accident, resulting from time skew (we even warn in the web UI about time), and we return results as described above.
> 
> As you might have noticed, [Grafana is now using future query times deliberately](https://github.com/grafana/grafana/pull/10434). It is doing so for consistently aligned query times in range queries, e.g. a range query with a step length of 30s will query for data points at the full and half minute always. To not miss the most recent data, Grafana will, in this case, query for up to 30s into the future and then (presumably) still cut the displayed graph to the present. This strategy collides with the implications I have listed above, creating [issues](https://github.com/grafana/grafana/issues/13419).
> 
> One might argue that Grafana's approach here is simply wrong, and indeed, the feature is somewhat controversial, see the [discussion in the relevant PR](https://github.com/grafana/grafana/pull/10434).
> However, it triggered some thinking on my side if we should handle queries from the future in a different way. Even if we disregard Grafana's current use case, there will be more that will ask Prometheus to predict the future, accidentally or deliberately.
> 
> Mutually exclusive options that come to mind:
> 
> 1. Refuse queries from the future (with a certain grace period in the order of seconds at most).
> 2. Don't return results for the future, i.e. no results at all for an instant query (with the same grace period again) and only return results for timestamps in the past for range queries, e.g. if a range query requests timestamps _t–40s_, _t–10s_, _t+20s_, and _t+50s_, only return results for _t–40s_ and _t–10s_
> 3. Adjust future timestamps to the present, i.e. an instant query for _t+20s_ will return the result for _t0s_, **timestamped as such**, while a range query will coalesce all timestamps in the future into one at _t0s_, for which it will return a result, **timestamped as such**, e.g. if a range query requests timestamps _t–40s_, _t–10s_, _t+20s_, and _t+50s_, return results for _t–40s_, _t–10s_, and _t0s_.
> 
> There are certainly many pros and cons. 1. would break current Grafana hard. 2. would directly counteract Grafana's strategy to also get the freshest result. 3. has the advantage that it does what probably most deliberate users of future timestamps want.
> 
> Of course, there is the overarching question if this is a breaking change only possible in Prometheus 3, even if we believe it is a change we want.

I have set the query.lookbackDelta=5s。 why I still get the data of future 5m.
![image](https://user-images.githubusercontent.com/5336915/89610389-f2efd580-d8ac-11ea-8667-a2f8a6973b81.png)
current time is:
![image](https://user-images.githubusercontent.com/5336915/89610409-fdaa6a80-d8ac-11ea-9fbd-62d62a9d5cc0.png)

**Comment by beorn7** [comment]
FYI: There was some troubleshooting happening behind the scenes. The outcome was that Prometheus behaves correctly and the graph shown in the previous comment only happens when Grafana and/or Thanos is in the game. @husoule filed https://github.com/thanos-io/thanos/issues/3001 and https://github.com/grafana/grafana/issues/26864 for further troubleshooting, but we are confident there is nothing weird happening in Prometheus.

**Comment by husoule** [comment]
> FYI: There was some troubleshooting happening behind the scenes. The outcome was that Prometheus behaves correctly and the graph shown in the previous comment only happens when Grafana and/or Thanos is in the game. @husoule filed [thanos-io/thanos#3001](https://github.com/thanos-io/thanos/issues/3001) and [grafana/grafana#26864](https://github.com/grafana/grafana/issues/26864) for further troubleshooting, but we are confident there is nothing weird happening in Prometheus.

Yes, I have ruled out the problem with prometheus. It is as expected.  After investigation, the data obtained through thanos query is inconsistent with the data obtained directly through promethues query.

**Comment by asuffield** [comment]
I spent about 15 minutes today discovering this behaviour - I can confirm that it is surprising and undesirable, and seems to provide nothing more than a source of low-entropy random numbers. The built-in graph UI will happily render future nonsense alongside real results without any indication of what it's doing. Option 3 seems like the most natural result to me, any chance we can arrange for that?

**Comment by beorn7** [comment]
We just encountered this during the bug scrub.

In very general, ever since Grafana changed its strategy, this doesn't seem to have bothered very many. We could simply close this.

However, Prometheus 3.x is being planned right now, so we would like to bring this to the attention of the Prometheus v3 coordination team. We have added it to the Prometheus 3 project. Please vet if we want to implement one (or more) of the solution proposed above. If not, feel free to close this for good.

Additional thought: We now utilize warnings AKA annotations in the query response. We could also add one of those.

**Comment by asuffield** [comment]
I'd be +1 on warning annotation for this, it's mostly a problem because it's surprising when it happens by accident

**Comment by beorn7** [comment]
Yeah, `@` with future timestamp can actually be a meaningful use case (if you craft some function that is actually meant to predict the future). From that perspective, it might also be useful to intentionally send a request with `time` set to the future. Or even range queries. This could be done for a dashboard that shows the disk usage from the past and a projection for the future.

We could still attach an info level annotation in that case. That would make sense if the accidental usage of future timestamps is happening more often than the deliberate one (because even info level annotations should not be false positives most of the time).

In any case, I would now conclude we should _not_ change the core behavior. Adding an info annotation is something I wouldn't see as a breaking change, so we can un-link this issue from the v3 effort.

I'll also change the title of this issue.

**Comment by beorn7** [comment]
About @jan--f 's other questions:

> Is the time parameter still needed given that @ is stable?

Yes. `time` is for the whole query, `@` is for a selector. They are in a way opposites of each other. While you could emulate a `time` setting by adding an `@` to every single selector in the query, it would be very verbose and also render that query useless for range queries.

> Should they behave the same way after this change, i.e. should up @ <some far future time> return nothing or return the latest samples?

I would say that `@` is a power user feature. If you use it, you should know what you are doing. However, it's very common to have a `time` parameter in an instant query, and it is even required to have time parameters in a range query, so every user is exposed to them. Therefore, if at all, I would only add an info-level annotation if a query parameter is pointing to the future, but not if the argument of an `@` modifier is pointing to the future (which is actually quite common).

**Comment by krajorama** [comment]
Hello from the bug scrub!

Seems like this issue went through a lot of iterations and also info/warn annotations were added in the meantime by @zenador . Since we don't feel strongly about the necessity of the use case, we'll close the issue, but ask interested parties to open a new issue specifically for defining under what circumstances an info annotation should be emitted.

**Comment by husoule** [comment]
您好，您的邮件我已经收到。
